# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lee Sanghun
tagline:          ''
description:      ''
url:              http://zasfe.github.io
baseurl:          /hyde/

author:
  name:           'Lee Sanghun'
  url:            https://zasfe.com

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/zasfe/hyde
