# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lee Sanghun
tagline:          'On Lee Sanghun'
description:      'Lead Systems Engineer at GABIA'
url:              http://zasfe.github.io
baseurl:          /hyde/

author:
  name:           'Lee Sanghun'
  url:            https://zasfe.com

paginate:         1

# Custom vars
github:
  repo:           https://github.com/zasfe/hyde

my:
  til:           https://zasfe.github.io/Today-I-learned/
  linkedin:           https://www.linkedin.com/in/sanghun
